services:
  dsbg:
    build: .
    ports:
      - "8080:666"
    volumes:
      - ./docs:/app/docs
    command: [
      "./dsbg",
      "-title", "Dead Simple Blog Generator",
      "-description", "A Simple, Open-Source Tool to Create Your Static Blog and Broadcast Your Content.\n\n# TLDR\n\n`go install github.com/tesserato/dsbg@latest` or download a [pre-built binary](https://github.com/tesserato/dsbg/releases)\n\n`dsbg -h` for usage instructions\n\nCheck the Readme [here](https://tesserato.github.io/dsbg/01readme/index.html) or at the Github [repo](https://github.com/tesserato/dsbg) for more details\n\nThis is a sample blog created with DSBG from the source at [github.com/tesserato/dsbg](https://github.com/tesserato/dsbg/tree/main/sample_content)\n\n[![Release Status](https://img.shields.io/github/release/tesserato/dsbg)](https://github.com/tesserato/dsbg/releases)\n\n[![License](https://img.shields.io/github/license/tesserato/dsbg)](https://github.com/tesserato/dsbg/blob/main/LICENSE)", 
      "-watch",
      "-input-path", "/app/sample_content", 
      "-output-path", "/app/docs", 
      "-base-url", "http://localhost:8080", 
      "-elements-top", "/app/analytics.html", 
      "-elements-bottom", "/app/giscus.html", 
      "-theme", "default",
      "-x-handle", "tesserato",
      "-bluesky-handle", "tesserato",
      "-threads-handle", "tesserato",
      "-mastodon-handle", "tesserato",
      "-telegram-handle", "tesserato",
      "-sort", "reverse-date-created"
    ]

    develop:
      watch:
        - action: rebuild
          path: .        # Watch the entire project directory
          target: /app   # In the container, changes in /app trigger rebuild
          ignore:
            - ./docs 
            - ./.git        
            - ./Dockerfile
            - ./docker-compose.yml
            - ./go.sum
            - ./go.mod